### PR TITLE
Updating angular 6 and fixing webpack issues and rxjs issue.

### PR DESCRIPTION
**Pull request by govi2010**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug Fix and Angular 6 update

* **What is the current behavior?** (You can also link to an open issue here)
Currently its working angular 5 with web-pack 3

* **What is the new behavior (if this is a feature change)?**
Now its working angular 6 with web-pack 4

### CODE REVIEW

**Comment by gdi2290** [comment]
can you fix the ci which looks like a problem running the webpack bundle for tests

**Comment by govi2010** [comment]
Will check it tomorrow.

**Comment by govi2010** [comment]
@gdi2290  I have fixed ci issue.

**Comment by MartinMa** [comment]
Works fine here! 🎉

Good to merge in my opinion.

Windows 10
npm 6.0.1
node v8.11.2

As a sidenode. npm complains about a few security vulnerabilities found in the dev dependencies. But I assume most of them can't be fixed right away, because they are third-party dependencies.

```
[!] 86 vulnerabilities found [30118 packages audited]
    Severity: 5 Low | 75 Moderate | 5 High | 1 Critical
```

**Pull request merged**
