### PR TITLE
[WIP!!!] refactor: move to angular v5

### PR DESCRIPTION
**Pull request by shlomiassaf**
### ADDED:
A Demo of how to create a module that will not load on prod builds using environment.

npm script:
```bash
`npm run start:aot`
```
For AOT mode in the dev server.
Experimental and might not scale for large applications.

File `build-utils.js` in config directory with helpers for the build process that contain **logic**, this is different from `helpers.js` which are only "dumb" utilities.
 
### CHANGED:
 - Metadata is now passed to `common` config from parents (prod, dev) and it is based
on a base metadata (most of the metadata is acquired the same)
  - `DefinePlugin` was removed from `prod` and `dev` setups and moved to `common` since it is based entirely on metadata which is known to `common`

### Feedback:
 - Bump node requirement to >= 6.9.1
    Since `@angular/dev-kit/build-optimizer` has this requirement and it is now a dependency there's no point on support below that.

##### PROD:
 - `OptimizeJsPlugin` - let build optimizer take care of optimization
 - `NormalModuleReplacementPlugin` - Handled in environment

##### COMMON:
 - `CheckerPlugin` - No more awesome-typescript-loader
  

> Configuration code was cleaned up and all unused plugins were removed.

> Some comments were removed and might required revisiting

### CODE REVIEW

**Comment by shlomiassaf** [comment]
Tasks:

- [ ] Remove the loaders: `awesome-typescript-loader`, `ngx-router-loader` and `angular2-template-loader`
- [ ] Use `@ngtools/webpack` as a **ts** loader and `@angular-devkit/build-optimizer/webpack-loader` when compiling AOT (dev and prod)
- [ ] Use `NgcWebpackPlugin` (works with `@ngtools/webpack` loader)
- [ ] Use `PurifyPlugin` from `@angular-devkit/build-optimizer` when AOT + production
- [ ] add AOT option for watch mode (`npm run start:aot` or maybe default it based of perf, **we should aim to default it**)
- [ ] Find the optimal setup for `CommonsChunkPlugin` with the `build-optimizer`, especially for tree-shaking.
- [ ] Optimize `UglifyJS` plugin to work best with the `build-optimizer` (as done in cli)
- [ ] Move to `uglifyjs-webpack-plugin`
- [ ] Try to apply RXJS 5.5 ESM alias
- [ ] Implement proper dynamic `environment` module using `hostReplacementPaths`
- [ ] Make AOT work in server dev watch mode

**Comment by shlomiassaf** [comment]
Looks like CI is passing, the error is not related and happens due to node 9.1.1 and incompat npm version

**Comment by Pere-Mas-Casanovas** [comment]
Hi there,

First of all, thank you for your amazing work with angular-starter.

We are a small company in the Nederland using angular-starter as a bundle tool and we are considering upgrading to Angular 5. But since the current version does not support Angular 5 we would like to know whether the pull request is going to go through or not. We would like to stay with angular-starter.

Thanks for your time guys,
Pere.

**Comment by gdi2290** [comment]
@Pere-Mas-Casanovas I'll work on this update right now

**Comment by gdi2290** [comment]
ok I fixed everything and it's merged in master with these commits. I didn't do the `CommonsChunkPlugin` with the `build-optimizer` task though. HMR should be quick to add back in a few minutes

**Comment by gdi2290** [comment]
@Pere-Mas-Casanovas can you try master now

**Comment by Pere-Mas-Casanovas** [comment]
@gdi2290 Thank you very much. I will try now and let you know.

**Comment by kuhnroyal** [comment]
Thanks, working!
HMR would be really nice to have back in.

**Comment by Pere-Mas-Casanovas** [comment]
Thank you very much @gdi2290 Our apps work now with Angular 5 :+1:

**Comment by giampierobono** [comment]
OUR APP TOO! Great job guys! Thank you sooo much!

**Comment by garkuwa** [comment]
Thank you, great job:)  By the way, after upgrading I'm getting error when build prod and start prod server (even when I pulled latest version of starter and tried to run prod):

image

Any help?

**Comment by giampierobono** [comment]
Are you using target es2015 in tsconfig? I had that issue too. Fixed using es5.

If I did not misunderstand there is an issue with uglify (not sure).

**Comment by giampierobono** [comment]
I think I had this too building prod without AOT.

**Comment by garkuwa** [comment]
@giampierobono thanks for advise, but my "tsconfig.js" already have **target:"es5"** Also I have tried to comment **uglifyjs-webpack-plugin** in my webpack-prod config and and now I'm receiving when build and run prod:

**"Error: Unexpected value 'BrowserModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
    at syntaxError (compiler.js:466)
    at compiler.js:15088"**

So question still open.

**Comment by giampierobono** [comment]
Yes my previous message was wrong. I though it was the error I had yesterday because of uglify. 
The error you reported I had doing build prod without AOT if I am not wrong

**Comment by candidosales** [comment]
"Thank you very much @gdi2290 and @shlomiassaf  Our apps work now with Angular 5 " ² :smile:

**Comment by almothafar** [comment]
@shlomiassaf I think you forgot webpack.test.conf from migration, didn't you?

**Pull request closed without merging**
